### ISSUE TITLE
Couldn't resolve reference to EPackage... errors after initial git clone

### ISSUE THREAD

**Issue by MichaelJohnCoan** [amlModeling/caex-workbench#1]
After just an initial git clone, I get "Couldn't resolve reference to EPackage..." errors for:
import "https://www.dke.de/CAEX/215"
import "http://caex/anytype" as anytype
in CAEXtext.xtext
(see the screen shot)
![image](https://user-images.githubusercontent.com/7872418/41374719-f65d7232-6f21-11e8-9c3a-1bf432c91278.png)

**Comment by mattsse** [comment]
I suppose this occurs due to the missing xtext nature of the model projects and therefor the Xtext plugin can't resolve the imported models.
This should be easily fixed by converting the model plugins (caex.caex215, caex.caex30, caex.anytype) to a xtext project by: right clicking on them -> configure -> convert to xtext project

**Comment by MichaelJohnCoan** [comment]
That worked.  Thanks!
